### ISSUE TITLE
Write out entity/attribute info

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#13]
Depends on #3

**Comment by lindsayplatt** [comment]
For depth columns, note: https://github.com/padilla410/lake-temp-lstm-static-data-release/pull/15#discussion_r1082902908

**Comment by lindsayplatt** [comment]
I made pretty significant progress on this today. I thought I would need more input at this time, but I believe I just need one small thing:

@AndyMcAliley can you write out a brief description of the `ealstm_group` column and post it in a comment here? I renamed that from your metadata column, `lstm_group`. Just something short that says what the possible values are and what it means/how someone could use it. Here are two little examples:

> **driver_gcm_cell_no**: Cell number mapping to a grid cell id for each NetCDF file stored in "meteorological_inputs_GCM.zip", which contains the appropriate GCM meteorological data used for modeling each lake.
>
> **model_preds_ealstm_nldas**: TRUE or FALSE values saying whether or not the lake was modeled by the EA-LSTM model. All 62,966 lakes included in this study were modeled by EA-LSTM and this column only contains values of TRUE.

**Comment by AndyMcAliley** [comment]
**ealstm_group:** Which partition the lake belongs to. Options are Training, Validation, Testing, or None. Lakes in the Training partition were used to optimize neural network parameters. Validation lakes were used to choose hyperparameters. Testing lakes were used to evaluate final model performance. Lakes in the None partition were not used for any of these purposes, likely because they lack sufficient temperature observations.

**Comment by lindsayplatt** [comment]
Mostly complete with #24
